import 'package:bloc/bloc.dart';
import 'package:dio/dio.dart';
import 'package:equatable/equatable.dart';
import 'package:shopapp/models/seachmodel/seachmodel.dart';

import '../../constant.dart';
import '../../models/search.dart';

part 'search_state.dart';

class SearchCubit extends Cubit<SearchState> {
  SearchCubit() : super(SearchInitial());
  Autogenerated? results;

  void search({required String word})async{
    emit(SearchLoading());
    try{
      Dio dio = Dio(BaseOptions(
          baseUrl: 'https://student.valuxapps.com/api/',
          receiveDataWhenStatusError: true));
      dio.options.headers = {
        'lang': 'en',
        'Content-Type': 'application/json',
        'Authorization': tokenkey
      };
      await dio.post('products/search',data: {
        
        'text':word
      }).then((value) {
        results=Autogenerated.fromJson(value.data);
      }).catchError((onError){

      });
      emit(SearchSuccess(model: results!));
    }catch(e){
      emit(Searchfaluier());
    }
  }
}
